version: 2

project_name: kao

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: kao
    main: ./cmd/kao
    binary: kao
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: archives
    builds:
      - kao
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "merge conflict"
      - "^Merge pull request"
      - "^Merge branch"
